version: '3'
services:
  etcd:
    image: {{ ETCD_IMAGE }}
    deploy:
      resources:
        limits:
          cpu: '0.5'
          memory: 256M
    container_name: "etcd"
    labels:
      blc-app.plaeform: "blocface"
      blc-app.type: "system"
      blc-app.service: "blocface-etcd"
    restart: always
    volumes:
      - ./data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCDCTL_API: "3"
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_NAME: "etcd1" # 集群需要修改成etcd1,etcd2,etcd3
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://{{ HOST_IP }}:2380" # 集群需要修改成对应的IP
      ETCD_ADVERTISE_CLIENT_URLS: "http://{{ HOST_IP }}:2379" # 集群需要修改成对应的IP
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd=http://{{ HOST_IP }}:2380" # 集群例子: etcd1=http://{{etcd1}}:2380,etcd2=http://{{ HOST_IP }}:2380,etcd3=http://{{ HOST_IP }}:2380
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - "2379:2379/tcp"
      - "2380:2380/tcp"
networks:
  default:
    external:
      name: blocface-network
